/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;

/**
 *
 * @author Biben
 */
public class AddFaculty extends javax.swing.JPanel {

    /**
     * Creates new form AddFaculty
     */
    MySQLAPI api;
    ButtonGroup bGroup;
    LibrarySystem ugat;
     SimpleDateFormat sdf;
    public AddFaculty(LibrarySystem lib) {
        initComponents();
        
          this.ugat = lib;
         this.setSize(540, 310);
       this.setLocation(230, 5);
        this.setBackground(new Color(0,0,0,0));
        api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
        Date dNow=new Date();
        bGroup = new ButtonGroup();
        bGroup.add(rdoMale);
        bGroup.add(rdoFemale);
        sdf = new SimpleDateFormat("MM/dd/YYYY");
  
        
        //txtBirthdate.getCalendar()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtBirthdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddFac = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        txtID.setBackground(new Color(0,0,0,20));
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });
        add(txtID);
        txtID.setBounds(170, 60, 150, 30);

        txtFName.setBackground(new Color(0,0,0,20));
        add(txtFName);
        txtFName.setBounds(170, 100, 150, 30);

        txtMName.setBackground(new Color(0,0,0,20));
        add(txtMName);
        txtMName.setBounds(170, 140, 150, 30);

        txtLName.setBackground(new Color(0,0,0,20));
        add(txtLName);
        txtLName.setBounds(170, 180, 150, 30);

        txtAddress.setBackground(new Color(0,0,0,20));
        add(txtAddress);
        txtAddress.setBounds(170, 230, 360, 30);

        jPanel2.setBackground(new Color(0,0,0,0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 127)), "Birthdate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 127))); // NOI18N
        jPanel2.setLayout(null);

        txtBirthdate.setBackground(new Color(0,0,0,20));
        jPanel2.add(txtBirthdate);
        txtBirthdate.setBounds(10, 20, 180, 30);

        add(jPanel2);
        jPanel2.setBounds(330, 140, 200, 60);

        jLabel8.setForeground(new java.awt.Color(0, 0, 127));
        jLabel8.setText("Faculty ID");
        add(jLabel8);
        jLabel8.setBounds(70, 70, 100, 16);

        jPanel1.setBackground(new Color(0,0,0,0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 127)), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 127))); // NOI18N
        jPanel1.setLayout(null);

        rdoMale.setSelected(true);
        rdoMale.setText("Male");
        rdoMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdoMale);
        rdoMale.setBounds(10, 30, 90, 25);

        rdoFemale.setText("Female");
        jPanel1.add(rdoFemale);
        rdoFemale.setBounds(110, 30, 80, 25);

        add(jPanel1);
        jPanel1.setBounds(330, 50, 200, 80);

        jLabel5.setForeground(new java.awt.Color(0, 0, 127));
        jLabel5.setText("Last Name");
        add(jLabel5);
        jLabel5.setBounds(70, 190, 100, 16);

        jLabel6.setForeground(new java.awt.Color(0, 0, 127));
        jLabel6.setText("Address");
        add(jLabel6);
        jLabel6.setBounds(80, 240, 70, 16);

        jLabel7.setForeground(new java.awt.Color(0, 0, 127));
        jLabel7.setText("Middle Name");
        add(jLabel7);
        jLabel7.setBounds(70, 150, 100, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 127));
        jLabel4.setText("First Name");
        add(jLabel4);
        jLabel4.setBounds(70, 110, 100, 16);

        btnAddFac.setText("Add");
        btnAddFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFacActionPerformed(evt);
            }
        });
        add(btnAddFac);
        btnAddFac.setBounds(440, 270, 55, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 127));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("New Faculty");
        add(jLabel3);
        jLabel3.setBounds(10, 10, 520, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/headerAddBook.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conAddBookForm.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(60, 30, 470, 290);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    private void btnAddFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFacActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String fname = txtFName.getText();
        String lname = txtLName.getText();
        String mname = txtMName.getText();
        String address = txtAddress.getText();
        Date dt = this.txtBirthdate.getDate();
        Date dNow = new Date();
        int year = (dNow.getYear()-1900);
       // String bd = txtBirthdate.getDateFormatString();
        
        System.out.println(dt+"  ");
        String gender = "Male";
        if(rdoFemale.isSelected()){
        gender = "Female";
        }
        if(id.isEmpty()){
        
            LibrarySystem.showError("Faculty ID is required!", "Failed to add faculty", this);
        }
        else if(fname.isEmpty()){
            LibrarySystem.showError("First Name is required!", "Failed to add faculty", this);
        }else if(mname.isEmpty()){
            LibrarySystem.showError("Middle Name is required!", "Failed to add faculty", this);
        }else if(lname.isEmpty()){
            LibrarySystem.showError("Last Name is required!", "Failed to add faculty", this);
        }else if(address.isEmpty()){
            LibrarySystem.showError("Address is required!", "Failed to add faculty", this);
        }else if(dt==null){
            LibrarySystem.showError("Invalid birthdate!", "Failed to add faculty", this);
        }else if(year-(dt.getYear()-1900)<18){
            LibrarySystem.showError("This is a minor!", "Failed to add faculty", this);

        }else if(api.isExist("TblStudent", "stud_no", id)){
            LibrarySystem.showError("This faculty is already exist!", "Failed to add faculty", this);
        }else{
       Faculty f =new Faculty();
       f.setId(id);
        f.setFName(fname);
        f.setMName(mname);
        f.setLName(lname);
        f.setGender(gender);
        f.setBirthdate(sdf.format(dt));
        f.setAddedBy(Integer.parseInt(ugat.getLogged().getId()));
        f.setDateAdded(System.currentTimeMillis()+"");
        f.setAddress(address);
        
        int ch = LibrarySystem.showConfirmation("Are you sure to add this faculty ?", "Add Faculty", this);
        if(ch==0){
            api.insertFaculty(f);
        LibrarySystem.showMessage("Faculty successfully added!", "Add Faculty", this);
        this.clearFormAddFaculty();
        }
        
            //System.out.println("asnf adate "+sdf.format(dt));
        }
        
        
    }//GEN-LAST:event_btnAddFacActionPerformed

    public void clearFormAddFaculty(){
    txtFName.setText("");
    txtMName.setText("");
    txtLName.setText("");
    txtID.setText("");
    txtAddress.setText("");
    txtBirthdate.setDate(null);
    }
    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
        int haba = txtID.getText().length();
        if(((Character.isDigit(evt.getKeyChar())) && (haba<10))||(evt.getKeyCode()==8)){
        txtID.setEditable(true);
        }else{
        txtID.setEditable(false);
        }
    }//GEN-LAST:event_txtIDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtAddress;
    private com.toedter.calendar.JDateChooser txtBirthdate;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMName;
    // End of variables declaration//GEN-END:variables
}
