/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Biben
 */
public class AddStudent extends javax.swing.JPanel {

    /**
     * Creates new form AddStudent
     */
    MySQLAPI api;
    ButtonGroup bGroup;
    LibrarySystem ugat;
    public AddStudent(LibrarySystem lib) {
        initComponents();
        this.ugat = lib;
         this.setSize(540, 310);
       this.setLocation(230, 5);
        this.setBackground(new Color(0,0,0,0));
        api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
        Date dNow=new Date();
        bGroup = new ButtonGroup();
        bGroup.add(rdoMale);
        bGroup.add(rdoFemale);
        
        
         Calendar cal = new GregorianCalendar();
     int curYear = cal.getWeekYear()-12;
     
      
     for(int x=curYear;(curYear-30)<x;x--){
         cboYear.addItem(x);
     }
        
        
        ArrayList arr = api.getAllGradeSection();
       
        for(int x=0;x<arr.size();x++){
             String sect = arr.get(x).toString();
             if(!sect.equals(Student.GRADUATED)){
              cboSection.addItem(arr.get(x));
             }
       
        
      
        }//end of loop
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        cboSection = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHeaderTakip = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdoMale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdoFemale = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        cboDay = new javax.swing.JComboBox();
        cboMonth = new javax.swing.JComboBox();
        cboYear = new javax.swing.JComboBox();
        btnAddStud = new javax.swing.JButton();
        txtStudNo = new javax.swing.JTextField();
        lblTakipNgForm = new javax.swing.JLabel();

        setLayout(null);

        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Student No.");
        add(jLabel8);
        jLabel8.setBounds(60, 60, 80, 14);

        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("First Name");
        add(jLabel3);
        jLabel3.setBounds(60, 90, 80, 14);

        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Middle Name");
        add(jLabel2);
        jLabel2.setBounds(60, 120, 80, 14);

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Last Name");
        add(jLabel4);
        jLabel4.setBounds(60, 150, 80, 14);

        txtFName.setBackground(new Color(0,0,0,20));
        add(txtFName);
        txtFName.setBounds(140, 80, 150, 30);

        txtMName.setBackground(new Color(0,0,0,20));
        add(txtMName);
        txtMName.setBounds(140, 110, 150, 30);

        txtLName.setBackground(new Color(0,0,0,20));
        add(txtLName);
        txtLName.setBounds(140, 140, 150, 30);

        txtAddress.setBackground(new Color(0,0,0,20));
        add(txtAddress);
        txtAddress.setBounds(140, 220, 360, 30);

        cboSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Year & Section --" }));
        add(cboSection);
        cboSection.setBounds(140, 170, 150, 30);

        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Address");
        add(jLabel6);
        jLabel6.setBounds(60, 230, 70, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Student Form");
        add(jLabel7);
        jLabel7.setBounds(170, 10, 80, 14);

        lblHeaderTakip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/headerAddBook.png"))); // NOI18N
        lblHeaderTakip.setText("jLabel1");
        add(lblHeaderTakip);
        lblHeaderTakip.setBounds(0, 0, 540, 30);

        jPanel1.setBackground(new Color(0,0,0,0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(null);

        rdoMale.setText("Male");
        jPanel1.add(rdoMale);
        rdoMale.setBounds(120, 20, 60, 23);

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-70, 20, 80, 14);

        rdoFemale.setSelected(true);
        rdoFemale.setText("Female");
        jPanel1.add(rdoFemale);
        rdoFemale.setBounds(30, 20, 80, 20);

        add(jPanel1);
        jPanel1.setBounds(310, 160, 190, 50);

        jPanel2.setBackground(new Color(0,0,0,0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Birthdate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        cboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Day --", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(cboDay);
        cboDay.setBounds(40, 50, 100, 30);

        cboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Month --", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel2.add(cboMonth);
        cboMonth.setBounds(40, 20, 100, 30);

        cboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Year --" }));
        jPanel2.add(cboYear);
        cboYear.setBounds(40, 80, 100, 30);

        add(jPanel2);
        jPanel2.setBounds(310, 40, 190, 120);

        btnAddStud.setText("Add");
        btnAddStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudActionPerformed(evt);
            }
        });
        add(btnAddStud);
        btnAddStud.setBounds(410, 280, 51, 23);

        txtStudNo.setBackground(new Color(0,0,0,20));
        txtStudNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudNoActionPerformed(evt);
            }
        });
        txtStudNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStudNoKeyPressed(evt);
            }
        });
        add(txtStudNo);
        txtStudNo.setBounds(140, 50, 150, 30);

        lblTakipNgForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conAddBookForm.png"))); // NOI18N
        lblTakipNgForm.setText("jLabel2");
        add(lblTakipNgForm);
        lblTakipNgForm.setBounds(60, 28, 470, 290);
    }// </editor-fold>//GEN-END:initComponents

    
    
     public  void showError(String mess){
           JOptionPane.showMessageDialog(this,mess ,"Error",JOptionPane.ERROR_MESSAGE);

    }
    
     public void clearStudForm(){
         txtStudNo.setText("");
   txtFName.setText("");
         txtMName.setText("");
       txtLName.setText("");
       txtAddress.setText("");
     cboSection.setSelectedIndex(0);
       cboMonth.setSelectedIndex(0);
     cboDay.setSelectedIndex(0);
      cboYear.setSelectedIndex(0);
     
     }
    private void btnAddStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudActionPerformed
        // TODO add your handling code here:
        String fName = txtFName.getText();
        String studNo =txtStudNo.getText();
        String mName = txtMName.getText();
        String lName = txtLName.getText();
        String section = cboSection.getSelectedItem().toString();
        String month = cboMonth.getSelectedItem().toString();
        String day = cboDay.getSelectedItem().toString();
        String year = cboYear.getSelectedItem().toString();
        String gend="Female";
        if(rdoMale.isSelected()){
        gend = "Male";
        }
        
        String address = txtAddress.getText();
        
        if(studNo.isEmpty()){
        showError("Student number is empty!");
        }else if(fName.isEmpty()){
        showError("First Name is required!");
        }else if(mName.isEmpty()){
        showError("Middle Name is required!");
        }else if(lName.isEmpty()){
        showError("Last Name is required!");    
        
        }else if(cboSection.getSelectedIndex()==0){
                showError("Select specific section!");    
         }else if(address.isEmpty()){
          showError("Address is required!");    
        
         }else if(cboMonth.getSelectedIndex()==0){
          showError("Select specific month!");    
        
         }else if(cboDay.getSelectedIndex()==0){
          showError("Select specific day!");    
        
         }else if(cboYear.getSelectedIndex()==0){
          showError("Select specific year!");    
        
         }else if(api.isExist("TblStudent", "stud_no", studNo)){
         showError("Student number is already exist!"); 
         }else{
             String m = cboMonth.getSelectedIndex()+"";
             if(cboMonth.getSelectedIndex()<=9){
             m= "0"+cboMonth.getSelectedIndex();
             }
         String dt = m+"/"+day+"/"+year;
         String mes = "**** Student ****\n";
         mes += "Student No. : "+studNo;
         mes += "\nFullname : "+fName+" "+mName+" "+lName;
         mes += "\nGender : "+gend;
         mes += "\nBirthdate : "+dt;
         mes += "\nAddress : "+address;
         mes += "\nGrade-Section : "+section;
         
         int a=JOptionPane.showConfirmDialog(this.ugat, mes, "New Student", JOptionPane.YES_NO_OPTION);
            if(a==0){
 Student bago = new Student();
 bago.setStudentNum(studNo);
        bago.setFName(fName);
        bago.setLName(lName);
        bago.setMName(mName);
        bago.setGender(gend); 
        bago.setBirthdate(dt);
        bago.setStatus(Student.ON_SCHOOL);
        bago.setAddress(address);
        bago.setGradeSection(section);
        bago.setDateAdded(System.currentTimeMillis()+"");
        bago.setAddedBy(Integer.parseInt(LibrarySystem.logged.getId()));
        api.insertStudent(bago);
        this.clearStudForm();
                }

       
         }//end of ok steate
        
    }//GEN-LAST:event_btnAddStudActionPerformed

    private void txtStudNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudNoActionPerformed

    private void txtStudNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudNoKeyPressed
        // TODO add your handling code here:
        int haba = txtStudNo.getText().length();
        if(((Character.isDigit(evt.getKeyChar()))||(evt.getKeyCode()==8))&&(haba<10)){
 txtStudNo.setEditable(true);        
        }else{
        txtStudNo.setEditable(false);
        }
    }//GEN-LAST:event_txtStudNoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStud;
    private javax.swing.JComboBox cboDay;
    private javax.swing.JComboBox cboMonth;
    private javax.swing.JComboBox cboSection;
    private javax.swing.JComboBox cboYear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHeaderTakip;
    private javax.swing.JLabel lblTakipNgForm;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtStudNo;
    // End of variables declaration//GEN-END:variables
}
