/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Biben
 */
public class BookManipulate extends javax.swing.JPanel {

    /**
     * Creates new form BookManipulate
     */
    
    public ViewBookPanel viewBook;
    public ReturnBookPanel retBook;
    public AddBookPanel pnlAddBook;
    public OtherMaterials material;
    public final static Color SELECTED_COLOR = new Color(173,212 ,251);
    public final static Color DESELECTED_COLOR = new Color(224,224 ,224);
    public BookManipulate(LibrarySystem m) {
         viewBook = new ViewBookPanel(m);
        retBook = new ReturnBookPanel(m);
        material = new OtherMaterials(m);
        pnlAddBook = new AddBookPanel();
        
         this.add(pnlAddBook);
        this.add(viewBook);
       this.add(retBook);
       this.add(material);
      
        
       retBook.hide();
       pnlAddBook.hide();
      // viewBook.hide();
        initComponents();
        this.setSize(775, 331);
    // btnViewBorrow = new JButton("asasassasas");
  //   this.setBackground(new Color(0,0,0,0));
     
         btnViewBorrow.setBackground(SELECTED_COLOR);
        this.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewBorrow = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnMaterials = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setLayout(null);

        btnViewBorrow.setForeground(new java.awt.Color(0, 0, 153));
        btnViewBorrow.setText("View Books");
        btnViewBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBorrowActionPerformed(evt);
            }
        });
        add(btnViewBorrow);
        btnViewBorrow.setBounds(20, 40, 190, 30);

        btnAddBook.setForeground(new java.awt.Color(0, 0, 153));
        btnAddBook.setText("Add Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        add(btnAddBook);
        btnAddBook.setBounds(20, 120, 190, 30);

        btnReturn.setForeground(new java.awt.Color(0, 0, 153));
        btnReturn.setText("Borrowed Books");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        add(btnReturn);
        btnReturn.setBounds(20, 80, 190, 30);

        btnMaterials.setForeground(new java.awt.Color(0, 0, 153));
        btnMaterials.setText("Other Materials");
        btnMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialsActionPerformed(evt);
            }
        });
        add(btnMaterials);
        btnMaterials.setBounds(20, 160, 190, 30);

        jLabel1.setBackground(new Color(0,0,0,0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addbookpanel.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        
       // this.add(retBook);
        viewBook.hide();
        pnlAddBook.hide();
        material.hide();
        retBook.show();
         btnViewBorrow.setBackground(DESELECTED_COLOR);
       btnAddBook.setBackground(DESELECTED_COLOR);
       btnReturn.setBackground(SELECTED_COLOR);
       btnMaterials.setBackground(DESELECTED_COLOR);
        retBook.refreshReturn("*","*");
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnViewBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBorrowActionPerformed
        // TODO add your handling code here:
        retBook.hide();
        pnlAddBook.hide();
        material.hide();
        viewBook.show();
        btnViewBorrow.setBackground(SELECTED_COLOR);
       btnAddBook.setBackground(DESELECTED_COLOR);
       btnReturn.setBackground(DESELECTED_COLOR);
       btnMaterials.setBackground(DESELECTED_COLOR);
        viewBook.refreshTable("*","*");
    }//GEN-LAST:event_btnViewBorrowActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
       viewBook.hide();
       retBook.hide();
       material.hide();
       pnlAddBook.show();
        btnViewBorrow.setBackground(DESELECTED_COLOR);
       btnAddBook.setBackground(SELECTED_COLOR);
       btnReturn.setBackground(DESELECTED_COLOR);
       btnMaterials.setBackground(DESELECTED_COLOR);
        
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialsActionPerformed
        // TODO add your handling code here:
        viewBook.hide();
       retBook.hide();
       pnlAddBook.hide();
       material.show();
       material.refreshTableMaterial("*", "*");
        btnViewBorrow.setBackground(DESELECTED_COLOR);
       btnAddBook.setBackground(DESELECTED_COLOR);
       btnReturn.setBackground(DESELECTED_COLOR);
       btnMaterials.setBackground(SELECTED_COLOR);
    }//GEN-LAST:event_btnMaterialsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnMaterials;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnViewBorrow;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
