/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.util.Date;

/**
 *
 * @author Biben
 */
public class BorrowMaterial extends javax.swing.JPanel {

    /**
     * Creates new form BorrowMaterial
     */
    DialogLarge dlg;
    MySQLAPI api;
    Material mat;
    public BorrowMaterial(DialogLarge d,Material m) {
        initComponents();
        this.dlg = d;
        this.mat = m;
           dlg.setUndecorated(true);
        dlg.setSize(630,340);
        dlg.setLocation(300, 300);
        
        api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
        this.lblMat.setText(mat.getName());
        this.lblDateAdded.setText(lblDateAdded.getText()+new Date(Long.parseLong(mat.getDateAdded())).toGMTString());
        this.lblAddedBy.setText(lblAddedBy.getText()+api.getSpecificLibrarian(Integer.parseInt(mat.getAddedBy())).getFullName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDateAdded = new javax.swing.JLabel();
        lblAddedBy = new javax.swing.JLabel();
        txtFacultyId = new javax.swing.JTextField();
        btnBorrow = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        lblMat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMat.setForeground(new java.awt.Color(0, 0, 127));
        lblMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMat.setText("Material Name");
        add(lblMat);
        lblMat.setBounds(191, 35, 430, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(600, 3, 20, 16);

        lblDateAdded.setForeground(new java.awt.Color(0, 0, 127));
        lblDateAdded.setText("Date Added : ");
        add(lblDateAdded);
        lblDateAdded.setBounds(200, 80, 410, 16);

        lblAddedBy.setForeground(new java.awt.Color(0, 0, 127));
        lblAddedBy.setText("Added By : ");
        add(lblAddedBy);
        lblAddedBy.setBounds(200, 110, 410, 16);

        txtFacultyId.setBackground(new Color(0,0,0,20));
        txtFacultyId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFacultyIdKeyPressed(evt);
            }
        });
        add(txtFacultyId);
        txtFacultyId.setBounds(340, 190, 210, 40);

        btnBorrow.setText("Borrow");
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });
        add(btnBorrow);
        btnBorrow.setBounds(550, 190, 73, 40);

        jLabel3.setForeground(new java.awt.Color(0, 0, 127));
        jLabel3.setText("Student No./Faculty ID ");
        add(jLabel3);
        jLabel3.setBounds(180, 200, 140, 16);

        lblNote.setForeground(new java.awt.Color(0, 0, 127));
        lblNote.setText("Note : Must returned the materials within 24 hrs to avoid penalty.");
        add(lblNote);
        lblNote.setBounds(210, 250, 410, 16);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        bg.setText("jLabel1");
        add(bg);
        bg.setBounds(0, 0, 640, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtFacultyIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacultyIdKeyPressed
        // TODO add your handling code here:
        if((Character.isDigit(evt.getKeyChar()))||(evt.getKeyCode()==8)){
        
        txtFacultyId.setEditable(true);
        }else{
        txtFacultyId.setEditable(false);
        }
    }//GEN-LAST:event_txtFacultyIdKeyPressed

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        // TODO add your handling code here:
        String fac = txtFacultyId.getText();
        String com = mat.getId()+"-"+mat.getName();
        if(fac.isEmpty()){
        LibrarySystem.showError("Must enter a faculty id", "Borrow failed", this);
        }else if(!api.isExist("TblStudent", "stud_no", fac)){
        LibrarySystem.showError("This faculty/student is not existing!", "Borrow Failed",this);
        }else if( api.getCountOf("TblBorrowedMaterial", "borrowed_by", fac)>=3){
        Faculty faculty = api.getSpecificFaculty(Integer.parseInt(fac));
        LibrarySystem.showError("This faculty reach the maximum amount\nof borrowed materials!" , "Failed to borrowed material", this);
        }else{
            
            int bilang = api.getCountOf("TblBorrowedMaterial", "borrowed_by", fac);
            System.out.println("ang bilang is "+bilang);
             Faculty facul = api.getSpecificFaculty(Integer.parseInt(fac));
            int pi=LibrarySystem.showConfirmation(facul.getFullName()+". Are you sure to borrow "+com+" ?", "Borrow materials", this);
           
            if(pi==0){
            api.updateData("TblMaterial", "status_mat", Material.BORROWED, "material_id", mat.getId()+"");
            api.insertBorrowedMaterial(mat, LibrarySystem.logged , facul);
            LibrarySystem.showMessage(com+" successfully borrowed by "+facul.getFullName(), "Borrowed material", this);
          this.dlg.dispose();
            }
        }
    }//GEN-LAST:event_btnBorrowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddedBy;
    private javax.swing.JLabel lblDateAdded;
    private javax.swing.JLabel lblMat;
    private javax.swing.JLabel lblNote;
    private javax.swing.JTextField txtFacultyId;
    // End of variables declaration//GEN-END:variables
}
