/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Component;
import javax.swing.JDialog;

/**
 *
 * @author Biben
 */
public class CloseConfirmation extends javax.swing.JPanel {

    /**
     * Creates new form CloseConfirmation
     */
  //  JDialog myDia;
    public MyDialog dia;
    
    public CloseConfirmation(MyDialog comp) {
        initComponents();
        this.setSize(250, 200);
    this.dia = comp;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOKDia = new java.awt.Button();
        lblCloseDia = new javax.swing.JLabel();
        btnCancelDia = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        btnOKDia.setBackground(new java.awt.Color(153, 204, 255));
        btnOKDia.setForeground(new java.awt.Color(0, 0, 153));
        btnOKDia.setLabel("OK");
        btnOKDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKDiaActionPerformed(evt);
            }
        });
        add(btnOKDia);
        btnOKDia.setBounds(50, 110, 55, 24);

        lblCloseDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        lblCloseDia.setText("jLabel2");
        lblCloseDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseDiaMouseClicked(evt);
            }
        });
        add(lblCloseDia);
        lblCloseDia.setBounds(215, 7, 20, 15);

        btnCancelDia.setBackground(new java.awt.Color(153, 204, 255));
        btnCancelDia.setForeground(new java.awt.Color(0, 0, 153));
        btnCancelDia.setLabel("Cancel");
        btnCancelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDiaActionPerformed(evt);
            }
        });
        add(btnCancelDia);
        btnCancelDia.setBounds(130, 110, 55, 24);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Close the software?");
        add(jLabel2);
        jLabel2.setBounds(60, 70, 120, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/myConfi.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(-3, 0, 250, 153);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKDiaActionPerformed
        // TODO add your handling code here
        System.out.println("kile");
     if(this.dia!=null){
    this.dia.getRootPaneDialog().dispose();
     }
    }//GEN-LAST:event_btnOKDiaActionPerformed

    private void lblCloseDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseDiaMouseClicked
        // TODO add your handling code here:
        //this.dia.dispose();
     
    }//GEN-LAST:event_lblCloseDiaMouseClicked

    private void btnCancelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDiaActionPerformed
        // TODO add your handling code here:
        this.dia.disposeDialog();
    }//GEN-LAST:event_btnCancelDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCancelDia;
    private java.awt.Button btnOKDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCloseDia;
    // End of variables declaration//GEN-END:variables
}
