/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

/**
 *
 * @author Biben
 */
public class Confirmation extends javax.swing.JPanel {

    /**
     * Creates new form Confirmation
     */
    DialogLarge dlg;
    public static boolean ok=false;
    public Confirmation(DialogLarge d,String salita) {
        initComponents();
        this.dlg = d;
        this.dlg.setUndecorated(true);
        this.lblSaid.setText(salita);
        this.dlg.setSize(240,150);
        //this.dlg.setSize(250, 200);
       this.dlg.setLocation(450, 220);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaid = new javax.swing.JLabel();
        btnOk = new java.awt.Button();
        lblClose = new javax.swing.JLabel();
        btnCancel = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblSaid.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblSaid.setForeground(new java.awt.Color(51, 0, 153));
        lblSaid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaid.setText("jLabel2");
        add(lblSaid);
        lblSaid.setBounds(0, 70, 240, 20);

        btnOk.setBackground(new java.awt.Color(153, 204, 255));
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOk.setForeground(new java.awt.Color(0, 0, 153));
        btnOk.setLabel("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        add(btnOk);
        btnOk.setBounds(60, 110, 60, 24);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        lblClose.setText("jLabel2");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        add(lblClose);
        lblClose.setBounds(215, 7, 20, 15);

        btnCancel.setBackground(new java.awt.Color(153, 204, 255));
        btnCancel.setForeground(new java.awt.Color(0, 0, 153));
        btnCancel.setLabel("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel);
        btnCancel.setBounds(140, 110, 55, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/myConfi.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(-3, 0, 240, 150);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        this.setState(true);
        this.dlg.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
     this.setState(false);
        this.dlg.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    public void setState(boolean o){
    this.ok = o;
    }
    
    public boolean getState(){
    return this.ok;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCancel;
    private java.awt.Button btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblSaid;
    // End of variables declaration//GEN-END:variables
}
