/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

/**
 *
 * @author Biben
 */
public class ForgotPassword extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPassword
     */
    DialogLarge rootDlg;
    LoginForm login;
    MySQLAPI api;
    public ForgotPassword(DialogLarge dlg,LoginForm log) {
        initComponents();
        this.rootDlg = dlg;
        this.login = log;
        rootDlg.setLocation(100, 100);
        rootDlg.setSize(630, 340);
        rootDlg.setUndecorated(true);
          this.api = new  MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnswer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnForgot = new javax.swing.JButton();
        lblCloseForgot = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(txtAnswer);
        txtAnswer.setBounds(300, 190, 260, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Forgot Password");
        add(jLabel2);
        jLabel2.setBounds(370, 37, 130, 15);

        lblQuestion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(0, 0, 102));
        lblQuestion.setText("Questions");
        add(lblQuestion);
        lblQuestion.setBounds(200, 170, 360, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Answer ");
        add(jLabel3);
        jLabel3.setBounds(200, 200, 60, 14);

        btnForgot.setText("Submit");
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });
        add(btnForgot);
        btnForgot.setBounds(390, 240, 73, 23);

        lblCloseForgot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        lblCloseForgot.setText("jLabel4");
        lblCloseForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseForgotMouseClicked(evt);
            }
        });
        add(lblCloseForgot);
        lblCloseForgot.setBounds(600, 4, 20, 15);

        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(300, 120, 260, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Username");
        add(jLabel4);
        jLabel4.setBounds(200, 130, 70, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseForgotMouseClicked
        // TODO add your handling code here:
        this.rootDlg.dispose();
    }//GEN-LAST:event_lblCloseForgotMouseClicked
Librarian l;
    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
      // lblQuestion.setEnabled(false);
if(api.isExist("TblLibrarian", "username", txtUsername.getText())){
int id=api.getIdOfUsername(txtUsername.getText());
 l = api.getSpecificLibrarian(id);
lblQuestion.setText("Question : "+l.getQuestion());
    System.out.println("anf "+id);
    btnForgot.setEnabled(true);
}else{
    btnForgot.setEnabled(false);
lblQuestion.setText("This is not existing!");
}
//=);
        
    }//GEN-LAST:event_txtUsernameFocusLost

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        // TODO add your handling code here:
        if(l.getAnswer().equals(txtAnswer.getText())){
            System.out.println("Uki");
            this.login.executeLogin(txtUsername.getText());
            rootDlg.dispose();
            
        }else{
        LibrarySystem.showError("Answer incorrect!", this);
        }
    }//GEN-LAST:event_btnForgotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCloseForgot;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
