/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Biben
 */
public class LoginForm extends javax.swing.JPanel {

    /**
     * Creates new form LoginForm
     */
    LibrarySystem motherFrame;
    MySQLAPI api;
    public LoginForm(LibrarySystem mother) {
        initComponents();
        
        this.motherFrame = mother;
        
        this.setSize(775, 331);
      
       int dump = enter();
  api = new  MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
       if(!api.isDatabaseHaveProblem()){
       this.lblStatus.setText("State : Connected");
       }
     //  btnLogin.disable();
    }
    
   int enter(){
     KeyStroke keyEnter =  KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false);
  
    Action keySAction = new AbstractAction(){
      public  void actionPerformed(ActionEvent e)
      {
          System.out.println("print");
      // LoginForm.btnLoginMouseClicked(new MouseEvent());
      }
    };
   
 try{
     this.motherFrame.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyEnter, "Enter");
     this.motherFrame.getRootPane().getActionMap().put("Enter", keySAction);
  // this.getRootPane()
 }catch(Exception e){
     System.out.println(e.getMessage());
 }
   //this.getRootPane().getActionMap().put("Enter", keySAction);

        return 0;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLib = new javax.swing.JLabel();
        lblNewLibrarian = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUser = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblForgot = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setLayout(null);

        lblLib.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLib.setForeground(new java.awt.Color(51, 0, 153));
        lblLib.setText("Librarians");
        lblLib.setToolTipText("View the list of librarians");
        lblLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLib.setFocusCycleRoot(true);
        lblLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLibMouseClicked(evt);
            }
        });
        add(lblLib);
        lblLib.setBounds(50, 20, 70, 14);

        lblNewLibrarian.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNewLibrarian.setForeground(new java.awt.Color(51, 0, 153));
        lblNewLibrarian.setText("New Librarian?");
        lblNewLibrarian.setToolTipText("Register a new librarian");
        lblNewLibrarian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNewLibrarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewLibrarianMouseClicked(evt);
            }
        });
        add(lblNewLibrarian);
        lblNewLibrarian.setBounds(680, 20, 90, 14);

        txtUsername.setBackground(new Color(0,0,0,20));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(330, 90, 190, 30);

        txtPassword.setBackground(new Color(0,0,0,20));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setEchoChar('\u2022');
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(330, 125, 190, 30);

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 102));
        lblUser.setText("Username");
        add(lblUser);
        lblUser.setBounds(250, 100, 60, 14);

        btnLogin.setForeground(new java.awt.Color(0, 0, 102));
        btnLogin.setText("Log-In");
        btnLogin.setToolTipText("Log-In for existing librarian");
        btnLogin.setBorderPainted(false);
        btnLogin.setEnabled(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(400, 170, 63, 23);

        lblPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPass.setForeground(new java.awt.Color(0, 0, 102));
        lblPass.setText("Password");
        add(lblPass);
        lblPass.setBounds(250, 135, 60, 14);

        lblStatus.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 102));
        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disco.png"))); // NOI18N
        lblStatus.setText("State: Disconnected");
        add(lblStatus);
        lblStatus.setBounds(20, 308, 170, 20);

        lblForgot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblForgot.setForeground(new java.awt.Color(0, 0, 102));
        lblForgot.setText("Forgot password?");
        lblForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotMouseClicked(evt);
            }
        });
        add(lblForgot);
        lblForgot.setBounds(250, 170, 130, 14);

        lblLog.setBackground(new java.awt.Color(255, 255, 255));
        lblLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginform.png"))); // NOI18N
        lblLog.setText("jLabel2");
        lblLog.setAlignmentY(0.0F);
        add(lblLog);
        lblLog.setBounds(0, 0, 800, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void lblNewLibrarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewLibrarianMouseClicked
        // TODO add your handling code here:
        System.out.println("hello");
        DialogLarge lrg = new DialogLarge(this.motherFrame,"Librarian",true);
        lrg.coverFrame(motherFrame.getCoverBlur());
        lrg.addPanel(new AddLibrarian(lrg));
        lrg.executeDialog();
        lrg.hideCoverFrame(motherFrame.getCoverBlur());
    }//GEN-LAST:event_lblNewLibrarianMouseClicked

    public void login(){
    
           String pw =  txtPassword.getText();
        String un =  txtUsername.getText();
        
        int ret=api.login(un, pw);
        if(ret==1){
           //username not existing
                JOptionPane.showMessageDialog(this.motherFrame, "Either username or password are incorrect!","Failed to log-in", JOptionPane.ERROR_MESSAGE);

        }else if(ret==2){
             Librarian lib=api.getSpecificLibrarian(api.getIdOfUsername(un));
             String salita="Password are incorrect!";
             if((lib.getPosition().equals(Librarian.HEAD_LIBRARIAN))){
             salita="Either username or password are incorrect!";
             }
             
             int rem=0;
             if((lib.getAttempts()<3)&&(lib.getPosition().equals(Librarian.LIBRARIAN))){
             api.updateData("TblLibrarian", "attempts", String.valueOf(lib.getAttempts()+1), "librarian_id", lib.getId());
              Librarian bago=api.getSpecificLibrarian(api.getIdOfUsername(un));
                rem=3-bago.getAttempts();
                salita+="\nYou have "+rem+" more attempts ";
            }
        
              if((rem==0)&&(lib.getPosition().equals(Librarian.LIBRARIAN))){
                        salita="You are totally blocked! ";

             }
               JOptionPane.showMessageDialog(this.motherFrame,salita ,"Failed to log-in", JOptionPane.ERROR_MESSAGE); 
                 
        }else if(ret==0){
            //meanig ok state na
           
           Librarian lib=api.getSpecificLibrarian(api.getIdOfUsername(un));
            if(lib.getAttempts()==3){
            LibrarySystem.showError("You are totally blocked!", this);
            }else{
             this.executeLogin(un);
           
            }
          //  System.out.println("uki");
            
           
        }
        
        
      
            
          
            
        
        
    
    }
    
    public void executeLogin(String un){
    
         txtUsername.setText("");
            txtPassword.setText("");
            btnLogin.setEnabled(false);
            this.motherFrame.getLoginForm().hide();
            this.motherFrame.getHomeForm().show();
            this.motherFrame.getTakip().hide();
            
           int id = api.getIdOfUsername(un);
            LibrarySystem.logged = api.getSpecificLibrarian(id);
            this.motherFrame.getLogoutKey().setText("Log-out");
            motherFrame.getLogoutKey().show();
            if(LibrarySystem.logged.getPosition().equals(Librarian.HEAD_LIBRARIAN)){
            this.motherFrame.getAdminKey().setText("Manage");
            this.motherFrame.getAdminKey().show();
            }else{
             this.motherFrame.getAdminKey().hide();
            }
         //   this.motherFrame.getAdminKey().setText("Manage");
            this.motherFrame.getLabelLog().setText(LibrarySystem.logged.getFullName());
        
    }
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
     
    // login();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLibMouseClicked
        // TODO add your handling code here:
       DialogLarge viewLib = new DialogLarge(this.motherFrame,"View librarian",true);
       viewLib.addPanel(new ViewLibrarian(viewLib));
       viewLib.executeDialog();
    }//GEN-LAST:event_lblLibMouseClicked

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            //meaning hit enter
            
             if((txtUsername.getText().equals(""))||(txtPassword.getText().equals(""))){
                //btnLogin.setEnabled(false);

        }else{
            login();
            }
            
            
        
        }
        //System.out.println();
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void lblForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseClicked
        // TODO add your handling code here:
        
    DialogLarge dlg =new DialogLarge(this.motherFrame,"Forgot",true);
   dlg.addPanel(new ForgotPassword(dlg,this));
   dlg.executeDialog();
    }//GEN-LAST:event_lblForgotMouseClicked

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        
        if((txtUsername.getText().equals(""))||(txtPassword.getText().equals(""))){
                btnLogin.setEnabled(false);

        }else{
            btnLogin.setEnabled(true);
        }
        
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
          if((txtUsername.getText().equals(""))||(txtPassword.getText().equals(""))){
                btnLogin.setEnabled(false);

        }else{
            btnLogin.setEnabled(true);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            //meaning hit enter
            
            if((txtUsername.getText().equals(""))||(txtPassword.getText().equals(""))){
                //btnLogin.setEnabled(false);

        }else{
            login();
            }
            
            
        
        }
    }//GEN-LAST:event_txtUsernameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblLib;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblNewLibrarian;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
