/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Cursor;
import java.util.ArrayList;

/**
 *
 * @author Biben
 */
public class ManageMaterial extends javax.swing.JPanel {

    /**
     * Creates new form ManageMaterial
     */
    DialogLarge dlg;
    MySQLAPI api;
    public final static String STORED="STORED",BORROWED="BORROWED",ARCHIVE="ARCHIVE";
    public ManageMaterial(DialogLarge d) {
        initComponents();
        this.dlg = d;
             dlg.setUndecorated(true);
        dlg.setSize(630,340);
        dlg.setLocation(300, 300);
        
        api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
        
        ArrayList<Material> mat = api.getAllDistinctMaterial();
        for(int x=0;x<mat.size();x++){
        Material m=(Material)mat.get(x);
        cboMatName.addItem(m.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        cboMatName = new javax.swing.JComboBox();
        btnClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboQty = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setForeground(new java.awt.Color(0, 0, 127));
        jLabel2.setText("Material Name");
        add(jLabel2);
        jLabel2.setBounds(190, 150, 110, 16);

        btnAdd.setText("Add New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(360, 240, 90, 25);

        cboMatName.setEditable(true);
        add(cboMatName);
        cboMatName.setBounds(310, 140, 190, 30);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        btnClose.setText("jLabel3");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        add(btnClose);
        btnClose.setBounds(600, 5, 20, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 127));
        jLabel3.setText("Quantity");
        add(jLabel3);
        jLabel3.setBounds(220, 200, 80, 16);

        cboQty.setEditable(true);
        cboQty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cboQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboQtyKeyPressed(evt);
            }
        });
        add(cboQty);
        cboQty.setBounds(310, 190, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 127));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add New Material");
        jLabel4.setToolTipText("");
        add(jLabel4);
        jLabel4.setBounds(190, 38, 430, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String qty = cboQty.getSelectedItem().toString();
        Object name = cboMatName.getSelectedItem();
        
        if(name==null){
        LibrarySystem.showError("Must contain a material name!", "Failed to add Material", this);
        }else{
            boolean noError=true;
        try{
        Integer.parseInt(qty);
        }catch(Exception e){
        noError=false;
         LibrarySystem.showError("Invalid quantity !", "Failed to add Material", this);
        }
        if(noError){
            int ilan=Integer.parseInt(qty);
            if(ilan<=0){
                     LibrarySystem.showError("Invalid quantity !", "Failed to add Material", this);

            }else{
                int ch= LibrarySystem.showConfirmation("Are you sure to add new material?", "Add Material", this);
                 if(ch==0){
           
                for(int x=0;x<ilan;x++){
                    Material m =new Material();
                    m.setName(name.toString().trim().toUpperCase());
                    m.setDateAdded(System.currentTimeMillis()+"");
                    m.setAddedBy(LibrarySystem.logged.getId());
                  api.insertMaterial(m);
                }
                String que = "SELECT CONCAT('Material ID : ',material_id) as str_mat_id,CONCAT('Material Name : ',material_name) as str_mat_name,";
                        que+= "CONCAT('Date Acquired : ',"+api.convertDateFormat("date_added", MySQLAPI.FULL_DATE)+") as str_date FROM TblMaterial ORDER BY material_id  DESC LIMIT 0,"+ilan+" ";
               
                        System.out.println(que);
                        String bagoName = name.toString().replaceAll(" ", "");
                        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                        new ReportProcess().generateReport("MaterialTag.jrxml", "Material"+bagoName+".pdf",que);
                           this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        
                        LibrarySystem.showMessage("Successfully added the material", "Add Material", this);
                this.dlg.dispose();
                  }
            
            
            }//end of else pag mataas sa 5
       
        }//end of pag ala erorr
        
        }//end of else
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void cboQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboQtyKeyPressed
        // TODO add your handling code here:
//        cboQty.getSelectedItem().toString();
//        System.out.println("sht");
//        if((Character.isDigit(evt.getKeyChar())) || (evt.getKeyCode()==8))  {
//        cboQty.setEditable(true);
//        }else{
//        cboQty.setEditable(false);
//        }
    }//GEN-LAST:event_cboQtyKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel btnClose;
    private javax.swing.JComboBox cboMatName;
    private javax.swing.JComboBox cboQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
