/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.util.ArrayList;

/**
 *
 * @author Biben
 */
public class MoveStudent extends javax.swing.JPanel {

    /**
     * Creates new form MoveStudent
     */
    DialogLarge dlg;
    Student stud;
    MySQLAPI api;
    public MoveStudent(DialogLarge d,Student s) {
        initComponents();
        this.dlg = d;
        this.stud = s;
          api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
       dlg.setUndecorated(true);
         dlg.setSize(630,340);
        dlg.setLocation(300, 300);
        this.lblFullname.setText(stud.getFullName());
        ArrayList sec = api.getAllGradeSection();
        for(int x=0;x<sec.size();x++){
            String lm = sec.get(x).toString();
            if(!lm.equals(Student.FACULTY)){
                    this.cboSection.addItem(sec.get(x));

            }
        
        }
        //set the curetn sectio  of the student
        cboSection.setSelectedItem(stud.getGradeSection());
         if(stud.getStatus().equals(Student.GRADUATED)){
        cboSection.setSelectedItem(stud.getStatus());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFullname = new javax.swing.JLabel();
        lblLClose = new javax.swing.JLabel();
        cboSection = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMove = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setLayout(null);

        lblFullname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(0, 0, 127));
        lblFullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullname.setText("Fullname");
        add(lblFullname);
        lblFullname.setBounds(190, 40, 430, 14);

        lblLClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        lblLClose.setText("jLabel2");
        lblLClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLCloseMouseClicked(evt);
            }
        });
        add(lblLClose);
        lblLClose.setBounds(600, 5, 20, 15);

        add(cboSection);
        cboSection.setBounds(260, 150, 220, 40);

        jLabel1.setForeground(new java.awt.Color(0, 0, 127));
        jLabel1.setText("Move to");
        add(jLabel1);
        jLabel1.setBounds(190, 160, 60, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/studBig.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(40, 100, 110, 130);

        btnMove.setText("Move");
        btnMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveActionPerformed(evt);
            }
        });
        add(btnMove);
        btnMove.setBounds(510, 160, 59, 23);

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        lblBG.setText("jLabel1");
        add(lblBG);
        lblBG.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLCloseMouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_lblLCloseMouseClicked

    private void btnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveActionPerformed
        // TODO add your handling code here:
       String sect = this.cboSection.getSelectedItem().toString();
      
      if((sect.equals(Student.GRADUATED))&&(stud.getStatus().equals(Student.GRADUATED))){
        LibrarySystem.showError("This student is already graduated!", "Move Section", this);

      }else if((sect.equals(stud.getGradeSection()))&&(!(stud.getStatus().equals(Student.GRADUATED)))){
          LibrarySystem.showError("This is the current section the this student!", "Move Section", this);
      }
       else if(sect.equals(Student.GRADUATED)){
       int pi = LibrarySystem.showConfirmation("Are you sure to set this student as graduated? ", "Graduated", this);
       if(pi==0){
             api.insertGraduatedStudent(stud, LibrarySystem.logged);
      api.updateData("TblStudent", "status", Student.GRADUATED , "stud_no", stud.getStudentNo());
       LibrarySystem.showMessage("Successfully set as graduated!", "Graduated", this);
       this.dlg.dispose();
       }
       
       
       }else{
     int ch= LibrarySystem.showConfirmation("Are you sure to transfer this student to\n"+sect+"?", "Move Section", this);
     if(ch==0){
     api.updateData("TblStudent", "grade_sec", sect, "stud_no", this.stud.getStudentNo());
     if(stud.getStatus().equals(Student.GRADUATED)){
         api.deleteData("TblGraduated", "stud_no", stud.getStudentNo());
         api.updateData("TblStudent", "status", Student.ON_SCHOOL, "stud_no", stud.getStudentNo());
         
     }
     LibrarySystem.showMessage("Successfully moved to "+sect, "Move Section", this);
     this.dlg.dispose();
     }
       
       }
      //LibrarySystem.showConfirmation("Are you sure to move this student to ", TOOL_TIP_TEXT_KEY, dlg)
    }//GEN-LAST:event_btnMoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMove;
    private javax.swing.JComboBox cboSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblLClose;
    // End of variables declaration//GEN-END:variables
}
