/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.awt.Cursor;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Biben
 */
public class ReturnBookConfirm extends javax.swing.JPanel {

    /**
     * Creates new form ReturnBookConfirm
     */
    DialogLarge dl;
    Student stud;
    Book buk;
    Borrowed bo;
    int dayMissed=0;
    int cost=0;
     double price;
    final static long ONE_DAY_MILLI=86400000;
    final static double PENALTY_PRICE=10.00;
    MySQLAPI api;
    public ReturnBookConfirm(DialogLarge dlg,Student st,Book b,Borrowed bor) {
        initComponents();
        this.dl = dlg;
        this.stud = st;
        this.buk = b;
        this.bo = bor;
          api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");      
        dlg.setUndecorated(true);
        dlg.setSize(630,340);
        dlg.setLocation(300, 300);
      try{
        long kelan = Long.parseLong(bo.getDateBorrow());
       long ilan = (System.currentTimeMillis() - kelan);
       
       //System.out.print(System.currentTimeMillis() +" "+ kelan);
        long missedDay = (  ilan/ReturnBookConfirm.ONE_DAY_MILLI);
        this.dayMissed = (int)missedDay;
          System.out.println("ang palugit "+dayMissed);
        System.out.println("misdaye "+missedDay);
         price = missedDay * ReturnBookConfirm.PENALTY_PRICE;
        this.cost = (int)price;
        System.out.println(" ilan "+ilan+" miss "+missedDay);
       this.lblTitle.setText(buk.getTitle());
        this.lblAuthor.setText(lblAuthor.getText()+buk.getAuthor());
        this.lblISBN.setText(lblISBN.getText()+buk.getISBN());
        this.lblCopyNumber.setText(lblCopyNumber.getText()+buk.getCopyNumber());
        lblPub.setText(lblPub.getText()+buk.getPublisher());
        lblYear.setText(lblYear.getText()+buk.getYearPublished());
        
        lblBor.setText(lblBor.getText()+stud.getStudentNo()+" "+stud.getFullName());
        
        
        if(stud.getGradeSection().equals(Student.FACULTY)){
        
       lblSect.setText("Position : "+stud.getGradeSection());
        }else{
        lblSect.setText(lblSect.getText()+stud.getGradeSection());
        }
        
        
        
       lblDateBor.setText(lblDateBor.getText()+new Date(kelan).toLocaleString());
        lblPenalty.setText(lblPenalty.getText()+" =P= "+price);
      
        //this wuloud hide the bayd textfielde
        if(price<=0){
            
            txtCash.hide();
            lblCash.hide();
        }
      
      }catch(Exception e){
          System.out.println("pagconstrucnt ng Return buk confirm "+e.getMessage());
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblCopyNumber = new javax.swing.JLabel();
        lblBor = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        lblSect = new javax.swing.JLabel();
        lblPenalty = new javax.swing.JLabel();
        lblPub = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDateBor = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        lblCash = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Title");
        add(lblTitle);
        lblTitle.setBounds(194, 40, 420, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/libraryIconMediumStack.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(20, 80, 150, 170);

        lblISBN.setText("ISBN : ");
        add(lblISBN);
        lblISBN.setBounds(210, 100, 400, 16);

        lblAuthor.setText("Author : ");
        add(lblAuthor);
        lblAuthor.setBounds(210, 80, 400, 16);

        lblCopyNumber.setText("Copy Number : ");
        add(lblCopyNumber);
        lblCopyNumber.setBounds(210, 120, 400, 16);

        lblBor.setText("Borrower : ");
        add(lblBor);
        lblBor.setBounds(210, 190, 390, 16);

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        add(btnReturn);
        btnReturn.setBounds(480, 280, 71, 30);

        lblSect.setText("Grade - Section : ");
        add(lblSect);
        lblSect.setBounds(210, 210, 370, 16);

        lblPenalty.setText("Penalty : ");
        add(lblPenalty);
        lblPenalty.setBounds(210, 260, 200, 16);

        lblPub.setText("Publisher : ");
        add(lblPub);
        lblPub.setBounds(210, 140, 400, 16);

        lblYear.setText("Year : ");
        add(lblYear);
        lblYear.setBounds(210, 160, 120, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(600, 5, 20, 16);

        lblDateBor.setText("Date Borrowed : ");
        add(lblDateBor);
        lblDateBor.setBounds(210, 230, 410, 16);

        txtCash.setBackground(new Color(0,0,0,20));
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashKeyPressed(evt);
            }
        });
        add(txtCash);
        txtCash.setBounds(320, 280, 150, 30);

        lblCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCash.setText("Cash :  =P=");
        add(lblCash);
        lblCash.setBounds(210, 290, 100, 17);

        BG.setBackground(new Color(0,0,0,0));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        BG.setText("jLabel1");
        add(BG);
        BG.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dl.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
     try{
         String lm = txtCash.getText();
        // api.returnBook(bo);
         
        if(dayMissed<=0){
     
            String lib = LibrarySystem.logged.getFullName();
                String que = "SELECT  CONCAT('ID : ',S.stud_no) as stud_no,CONCAT('Fullname : ',S.f_name,' ',S.m_name,' ',S.l_name) as fullname, CONCAT('Date Borrowed : ',DATE_FORMAT(FROM_UNIXTIME(BOR.date_borrowed/1000),'%d/%m/%Y %h:%i%p' )) as date_bor ,";
                que+= " CONCAT('Book ISBN : ',B.isbn) as str_isbn, CONCAT('Copy Number : ',B.copy_number) as str_copy,CONCAT('Book Title : ',B.title) as str_title,  CONCAT('Penalty      =P= ','"+price+"') as penalty , ";
                que+= " CONCAT('Cash      =P= ','0.00') as cash , CONCAT('Change     =P= ','0.00') as changed_cash, CONCAT('Assess by : ','"+lib+"' ) as assess,  ";
                que+= " CONCAT('Date assess : ','"+new Date().toLocaleString()+"') as date_as ,CONCAT('LoveU Library',' ','System')as title_report, CONCAT('Official ','Reciept')as subtitle, ";
                que+=" CONCAT('Rate per missed day : ','"+api.getRatePerDay()+"') as rate , CONCAT('Missed day : ','"+dayMissed+"') as day_missed ";
                        que+= "  FROM TblBook B, TblBorrowed BOR,TblStudent S    WHERE BOR.borrow_id = "+bo.getBorrowID()+" ";
                        
                que+=" AND BOR.book_id = B.book_id AND S.stud_no = BOR.borrower ";
                    System.out.println(que);
                     this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
               new ReportProcess().generateReport("report3.jrxml", "report3.pdf", que);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            
                   api.returnBook(bo);


       JOptionPane.showMessageDialog(this, "Successfully return.", "Return book", JOptionPane.PLAIN_MESSAGE);
      this.dl.dispose();
            
        }else{
            if(lm.isEmpty()){
            LibrarySystem.showError("Invalid amount of penalty!", "Invalid amount", this);
            }else{
                int bayad = Integer.parseInt(lm);
                if(bayad<price){
                LibrarySystem.showError("Enter sufficient amount of penalty!", "Invalid amount", this);
                }else{
                
                    if(dayMissed>=1){
                        System.out.println("oh shet eto na");
                        api.addPenaltyRecord(stud.getStudentNo(), LibrarySystem.logged.getId(), this.cost, this.buk.getId());
                        System.out.println("ohh my godddd");
                    }
                double sukli = bayad-price;
             
              
                String lib = LibrarySystem.logged.getFullName();
                String que = "SELECT  CONCAT('ID : ',S.stud_no) as stud_no,CONCAT('Fullname : ',S.f_name,' ',S.m_name,' ',S.l_name) as fullname, CONCAT('Date Borrowed : ',DATE_FORMAT(FROM_UNIXTIME(BOR.date_borrowed/1000),'%d/%m/%Y %h:%i%p' )) as date_bor ,";
                que+= " CONCAT('Book ISBN : ',B.isbn) as str_isbn, CONCAT('Copy Number : ',B.copy_number) as str_copy,CONCAT('Book Title : ',B.title) as str_title,  CONCAT('Penalty      =P= ','"+price+"') as penalty , ";
                que+= " CONCAT('Cash      =P= ','"+bayad+"') as cash , CONCAT('Change     =P= ','"+sukli+"') as changed_cash, CONCAT('Assess by : ','"+lib+"' ) as assess,  ";
                que+= " CONCAT('Date assess : ','"+new Date().toLocaleString()+"') as date_as ,CONCAT('LoveU Library',' ','System')as title_report, CONCAT('Official ','Reciept')as subtitle, ";
                   que+=" CONCAT('Rate per missed day : ','"+api.getRatePerDay()+"') as rate , CONCAT('Missed day : ','"+dayMissed+"') as day_missed ";
                        que+= "  FROM TblBook B, TblBorrowed BOR,TblStudent S    WHERE BOR.borrow_id = "+bo.getBorrowID()+" ";
                        
                que+=" AND BOR.book_id = B.book_id AND S.stud_no = BOR.borrower ";
                    System.out.println(que);
                     this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
               new ReportProcess().generateReport("report3.jrxml", "report3.pdf", que);
                
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                api.returnBook(bo);
                   JOptionPane.showMessageDialog(this, "Successfully return.", "Return book", JOptionPane.PLAIN_MESSAGE);
                this.dl.dispose();
                }
            }
      
        
        
        }//meaning nmay penalth

       
     
     }catch(Exception e){
         System.out.println("Pagreturn --> "+e.getMessage());
           dl.dispose();
     }
        
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyPressed
        // TODO add your handling code here:
        String bayad=txtCash.getText();
        if((Character.isDigit(evt.getKeyChar()))||(evt.getKeyCode()==8)){
        txtCash.setEditable(true);
        }else{
        txtCash.setEditable(false);
        }
        
    }//GEN-LAST:event_txtCashKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblBor;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblCopyNumber;
    private javax.swing.JLabel lblDateBor;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblPenalty;
    private javax.swing.JLabel lblPub;
    private javax.swing.JLabel lblSect;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtCash;
    // End of variables declaration//GEN-END:variables
}
