/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.awt.Cursor;
import java.util.Date;

/**
 *
 * @author Biben
 */
public class ReturnMaterial extends javax.swing.JPanel {

    /**
     * Creates new form ReturnMaterial
     */
    DialogLarge dlg;
    BorrowedMaterial mat;
    MySQLAPI api;
    int day;
    double price;
     Material mater;
    public ReturnMaterial(DialogLarge d,BorrowedMaterial m) {
        initComponents();
           this.dlg = d;
        this.mat = m;
           dlg.setUndecorated(true);
        dlg.setSize(630,340);
        dlg.setLocation(300, 300);
        
        api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
        long kelan = Long.parseLong(mat.getDateBorrowed());
        Date dBor = new Date(kelan);
      long diff = api.getMilliNow()-kelan;
  
         day=(int)(diff/ReturnBookConfirm.ONE_DAY_MILLI);
        
        if(day<1){
            lblCash.hide();
            txtCash.hide();
        
        }
        Student st = api.getSpecificStudent(mat.getBorrower());
        Librarian lib = api.getSpecificLibrarian(mat.getAssessBy());
        mater = api.getSpecificMaterial(mat.getId());
        this.lblBorID.setText(lblBorID.getText()+mat.getId());
        this.lblMatTitle.setText(mater.getName());
        this.lblBorName.setText(lblBorName.getText()+st.getFullName());
        this.lblAssessBy.setText(lblAssessBy.getText()+lib.getFullName());
        this.lblGradeSec.setText(lblGradeSec.getText()+st.getGradeSection());
        if(st.getGradeSection().equals(Student.FACULTY)){
        lblGradeSec.setText("Position : "+st.getGradeSection());
        }
        this.lblDateBor.setText(lblDateBor.getText()+dBor.toLocaleString());
        this.lblPenalty.setText(lblPenalty.getText()+api.getPricePenalty(day, api.getRatePerDay()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatTitle = new javax.swing.JLabel();
        lblCash = new javax.swing.JLabel();
        lblAssessBy = new javax.swing.JLabel();
        lblGradeSec = new javax.swing.JLabel();
        lblBorID = new javax.swing.JLabel();
        lblDateBor = new javax.swing.JLabel();
        lblPenalty = new javax.swing.JLabel();
        lblBorName = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        txtCash = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblMatTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMatTitle.setForeground(new java.awt.Color(0, 0, 127));
        lblMatTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatTitle.setText("Title");
        add(lblMatTitle);
        lblMatTitle.setBounds(191, 35, 430, 20);

        lblCash.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCash.setForeground(new java.awt.Color(0, 0, 127));
        lblCash.setText("Cash : =P=");
        add(lblCash);
        lblCash.setBounds(190, 250, 110, 16);

        lblAssessBy.setForeground(new java.awt.Color(0, 0, 127));
        lblAssessBy.setText("Assess By : ");
        add(lblAssessBy);
        lblAssessBy.setBounds(190, 130, 420, 16);

        lblGradeSec.setForeground(new java.awt.Color(0, 0, 127));
        lblGradeSec.setText("Grade - Section : ");
        add(lblGradeSec);
        lblGradeSec.setBounds(190, 110, 420, 16);

        lblBorID.setForeground(new java.awt.Color(0, 0, 127));
        lblBorID.setText("Borrowers ID : ");
        add(lblBorID);
        lblBorID.setBounds(190, 70, 430, 16);

        lblDateBor.setForeground(new java.awt.Color(0, 0, 127));
        lblDateBor.setText("Date Borrowed :");
        add(lblDateBor);
        lblDateBor.setBounds(190, 180, 440, 16);

        lblPenalty.setForeground(new java.awt.Color(0, 0, 127));
        lblPenalty.setText("Penalty : =P= ");
        add(lblPenalty);
        lblPenalty.setBounds(190, 200, 440, 16);

        lblBorName.setForeground(new java.awt.Color(0, 0, 127));
        lblBorName.setText("Borrowed By :");
        add(lblBorName);
        lblBorName.setBounds(190, 90, 430, 16);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        lblClose.setText("jLabel2");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        add(lblClose);
        lblClose.setBounds(600, 5, 20, 16);

        btnPay.setText("Return");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        add(btnPay);
        btnPay.setBounds(470, 240, 90, 30);

        txtCash.setBackground(new Color(0,0,0,20));
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashKeyPressed(evt);
            }
        });
        add(txtCash);
        txtCash.setBounds(310, 240, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyPressed
        // TODO add your handling code here:
        if((Character.isDigit(evt.getKeyChar()))||(evt.getKeyCode()==8)){
        txtCash.setEditable(true);
        }else if(evt.getKeyCode()==10){
            System.out.println("shittttttt ");
        
        }else{
        txtCash.setEditable(false);
        }
    }//GEN-LAST:event_txtCashKeyPressed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        System.out.println("ang day "+day+"    "+mat.getMissedDay());
        if (mat.getMissedDay()>=api.getDayExpire()){
            double pric = mat.getPenaltyCost();
            String bayad = txtCash.getText();
            double pay = Double.parseDouble(bayad);
            if(bayad.isEmpty()){
            LibrarySystem.showError("Enter your cash", "Failed to return",this);
            }else if(pay<pric){
             LibrarySystem.showError("Enter a sufficient cash!", "Failed to return",this);
            }else{
                String idStr = "Student Number : ";
                Student st  = api.getSpecificStudent(mat.getBorrower());
                if(st.getStatus().equals(Student.FACULTY)){
                idStr = "Faculty ID : ";
                }
                String ass = LibrarySystem.logged.getFullName();
                double sukli = pay - pric;
                
                 String que = "SELECT CONCAT('"+idStr+"',S.stud_no) as id, CONCAT('Fullname ',S.f_name,' ',S.m_name,' ',S.l_name) as borrower , ";
            que+="CONCAT('Date Borrowed : ',DATE_FORMAT(FROM_UNIXTIME(BM.date_borrowed/1000),'%d/%m/%Y %h:%i%p' )) as date_bor, CONCAT('Material ID : ',M.material_id) as mat_id, ";
            que+="CONCAT('Material Name : ',M.material_name) as mat_name, CONCAT('Rate per missed day : =P= ','"+api.getRatePerDay()+"')as rate, CONCAT('Cash :  =P= ','"+bayad+"') as  cash ,";
            que+="CONCAT('Penalty : =P= ','"+mat.getPenaltyCost()+"') as penalty,CONCAT('Change : =P= ','"+sukli+"')as change_cash, CONCAT('Asses by : ','"+ass+"')as assess_by ,";
            que+="CONCAT('Date Assess : ',DATE_FORMAT(FROM_UNIXTIME("+api.getMilliNow()+"/1000),'%d/%m/%Y %h:%i%p' )) as date_assess,  ";
            que+="CONCAT('LoveU Library ',' System') as title_report, CONCAT('Official ','Reciept')as subtitle ,CONCAT('Missed day : ','"+mat.getMissedDay()+"') as day_missed  ";
            que+="FROM TblStudent S ,TblBorrowedMaterial BM, TblMaterial M WHERE ";
            que+= " S.stud_no = BM.borrowed_by AND M.material_id = BM.material_id AND M.material_id = "+mat.getId()+" ";
               this.setCursor(new Cursor(Cursor.WAIT_CURSOR)); 
                new ReportProcess().generateReport("ReceiptMaterial.jrxml", "ReceiptMaterial.pdf", que);
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
              LibrarySystem.showMessage(mater.getId()+"-"+mater.getName()+" successfully return!","Return Material", this);
            api.returnMaterial(mater);
                api.addPenaltyRecordMaterial(mat, LibrarySystem.logged);
            this.dlg.dispose();
            
            }
        }else{
            //System.out.println("oh ywar"); 
          //Mat  m = api.getSpecificMaterial(mat.getId());
            Student sino = api.getSpecificStudent(mat.getBorrower());
            String ass = LibrarySystem.logged.getFullName();
            String idStr = "Student Number : ";
            if(sino.getGradeSection().equals(Student.FACULTY)){
            idStr = "Faculty ID : ";
            }
            String que = "SELECT CONCAT('"+idStr+"',S.stud_no) as id, CONCAT('Fullname ',S.f_name,' ',S.m_name,' ',S.l_name) as borrower , ";
            que+="CONCAT('Date Borrowed : ',DATE_FORMAT(FROM_UNIXTIME(BM.date_borrowed/1000),'%d/%m/%Y %h:%i%p' )) as date_bor, CONCAT('Material ID : ',M.material_id) as mat_id, ";
            que+="CONCAT('Material Name : ',M.material_name) as mat_name, CONCAT('Rate per missed day : =P= ','"+api.getRatePerDay()+"')as rate, CONCAT('Cash :  =P= ','0.00') as  cash ,";
            que+="CONCAT('Penalty : =P= ','0.00') as penalty,CONCAT('Change : =P= ','0.00')as change_cash, CONCAT('Asses by : ','"+ass+"')as assess_by ,";
            que+="CONCAT('Date Assess : ',DATE_FORMAT(FROM_UNIXTIME("+api.getMilliNow()+"/1000),'%d/%m/%Y %h:%i%p' )) as date_assess,  ";
            que+="CONCAT('LoveU Library ',' System') as title_report, CONCAT('Official ','Reciept')as subtitle,CONCAT('Missed day : ','"+mat.getMissedDay()+"') as day_missed    ";
            que+="FROM TblStudent S ,TblBorrowedMaterial BM, TblMaterial M WHERE ";
            que+= " S.stud_no = BM.borrowed_by AND M.material_id = BM.material_id AND M.material_id = "+mat.getId()+" ";
            System.out.println(que);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            new ReportProcess().generateReport("ReceiptMaterial.jrxml", "ReceiptMaterial.pdf", que);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            LibrarySystem.showMessage(mater.getId()+"-"+mater.getName()+" successfully return!","Return Material", this);
            api.returnMaterial(mater);
            this.dlg.dispose();
        }
    }//GEN-LAST:event_btnPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAssessBy;
    private javax.swing.JLabel lblBorID;
    private javax.swing.JLabel lblBorName;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDateBor;
    private javax.swing.JLabel lblGradeSec;
    private javax.swing.JLabel lblMatTitle;
    private javax.swing.JLabel lblPenalty;
    private javax.swing.JTextField txtCash;
    // End of variables declaration//GEN-END:variables
}
