/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

/**
 *
 * @author Biben
 */
public class StudentLogged extends javax.swing.JPanel {

    /**
     * Creates new form StudentLogged
     */
    DialogLarge dlg;
    Student stud;
    MySQLAPI api;
    public StudentLogged(DialogLarge d,Student s) {
        initComponents();
       this.dlg = d;
       this.stud = s;
       api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
       dlg.setUndecorated(true);
         dlg.setSize(630,340);
        dlg.setLocation(300, 300);
        lblStudId.setText( lblStudId.getText()+" "+stud.getStudentNo());
        lblFullname.setText(stud.getFullName());
         lblBirthdate.setText( lblBirthdate.getText()+" "+stud.getBirthdate());
        lblSection.setText(lblSection.getText()+" "+stud.getGradeSection());
        
        if(stud.getStatus().equals(Student.GRADUATED)){
        lblSection.setText("Grade - Section : None(GRADUATED)");
        }
        lblStatus.setText(lblStatus.getText()+" "+stud.getStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimeIn = new javax.swing.JButton();
        lblFullname = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblStudId = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setLayout(null);

        btnTimeIn.setText("Time-In");
        btnTimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeInActionPerformed(evt);
            }
        });
        add(btnTimeIn);
        btnTimeIn.setBounds(370, 280, 100, 23);

        lblFullname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(0, 0, 153));
        lblFullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullname.setText("Fullname");
        add(lblFullname);
        lblFullname.setBounds(194, 40, 420, 14);

        lblSection.setText("Year-Section : ");
        add(lblSection);
        lblSection.setBounds(190, 100, 420, 14);

        lblBirthdate.setText("Birthdate :");
        add(lblBirthdate);
        lblBirthdate.setBounds(190, 150, 420, 14);

        lblStatus.setText("Status : ");
        add(lblStatus);
        lblStatus.setBounds(190, 120, 420, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/studBig.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(40, 110, 120, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(600, 5, 20, 15);

        lblStudId.setText("Student Number : ");
        add(lblStudId);
        lblStudId.setBounds(190, 70, 420, 14);

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/emptyPopup.png"))); // NOI18N
        lblBG.setText("jLabel1");
        add(lblBG);
        lblBG.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnTimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeInActionPerformed
        // TODO add your handling code here:
        api.insertStudentLog(stud, LibrarySystem.logged);
        LibrarySystem.showMessage("Successfully logged!", "Log", this);
        this.dlg.dispose();
    }//GEN-LAST:event_btnTimeInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimeIn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStudId;
    // End of variables declaration//GEN-END:variables
}
