/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;

/**
 *
 * @author Biben
 */
public class StudentManipulate extends javax.swing.JPanel {

    /**
     * Creates new form StudentManipulate
     */
    ViewStudent view;
    AddStudent addStud;
    AddFaculty fac;
    ViewFaculty viewFac;
    public StudentManipulate(LibrarySystem m){ 
          this.view =  new ViewStudent(m);
         this.addStud = new AddStudent(m);
         this.fac = new AddFaculty(m);
        this.viewFac =  new ViewFaculty(m);
          this.add(view);
          this.add(addStud);
          this.add(fac);
          this.add(viewFac);
        initComponents();
        this.setSize(775, 331);
        addStud.hide();
        fac.hide();
        viewFac.hide();
        this.setBackground(new Color(0,0,0,0));
        btnViewStud.setBackground(BookManipulate.SELECTED_COLOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewStud = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        btnFaculty = new javax.swing.JButton();
        btnViewFaculty = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setLayout(null);

        btnViewStud.setForeground(new java.awt.Color(0, 0, 153));
        btnViewStud.setText("Students");
        btnViewStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudActionPerformed(evt);
            }
        });
        add(btnViewStud);
        btnViewStud.setBounds(20, 40, 190, 30);

        btnAddStudent.setForeground(new java.awt.Color(0, 0, 153));
        btnAddStudent.setText("New Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        add(btnAddStudent);
        btnAddStudent.setBounds(20, 80, 190, 30);

        btnFaculty.setForeground(new java.awt.Color(0, 0, 153));
        btnFaculty.setText("New Faculty");
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });
        add(btnFaculty);
        btnFaculty.setBounds(20, 160, 190, 30);

        btnViewFaculty.setForeground(new java.awt.Color(0, 0, 153));
        btnViewFaculty.setText("Faculty");
        btnViewFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFacultyActionPerformed(evt);
            }
        });
        add(btnViewFaculty);
        btnViewFaculty.setBounds(20, 120, 190, 30);

        jLabel1.setBackground(new Color(0,0,0,0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addbookpanel.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudActionPerformed
        // TODO add your handling code here:
       this.addStud.hide();
         this.fac.hide();
         this.viewFac.hide();
        this.view.show();
        this.view.refreshTable("*", "*");
        btnViewStud.setBackground(BookManipulate.SELECTED_COLOR);
        btnAddStudent.setBackground(BookManipulate.DESELECTED_COLOR);
        btnViewFaculty.setBackground(BookManipulate.DESELECTED_COLOR);
        btnFaculty.setBackground(BookManipulate.DESELECTED_COLOR);
        
    }//GEN-LAST:event_btnViewStudActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        this.view.hide();
         this.fac.hide();
         this.viewFac.hide();
        this.addStud.show();
        btnViewStud.setBackground(BookManipulate.DESELECTED_COLOR);
        btnAddStudent.setBackground(BookManipulate.SELECTED_COLOR);
        btnViewFaculty.setBackground(BookManipulate.DESELECTED_COLOR);
        btnFaculty.setBackground(BookManipulate.DESELECTED_COLOR);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        // TODO add your handling code here:
        
        
        this.view.hide();
        this.addStud.hide();
        this.viewFac.hide();
        this.fac.show();
        btnViewStud.setBackground(BookManipulate.DESELECTED_COLOR);
        btnAddStudent.setBackground(BookManipulate.DESELECTED_COLOR);
        btnViewFaculty.setBackground(BookManipulate.DESELECTED_COLOR);
        btnFaculty.setBackground(BookManipulate.SELECTED_COLOR);
    }//GEN-LAST:event_btnFacultyActionPerformed

    private void btnViewFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFacultyActionPerformed
        // TODO add your handling code here:
         this.view.hide();
        this.addStud.hide();
        this.fac.hide();
        this.viewFac.show();
        this.viewFac.refreshFaculty("*", "*");
        btnViewStud.setBackground(BookManipulate.DESELECTED_COLOR);
        btnAddStudent.setBackground(BookManipulate.DESELECTED_COLOR);
         btnViewFaculty.setBackground(BookManipulate.SELECTED_COLOR);
        btnFaculty.setBackground(BookManipulate.DESELECTED_COLOR);
        
    }//GEN-LAST:event_btnViewFacultyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JButton btnViewFaculty;
    private javax.swing.JButton btnViewStud;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
