/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Biben
 */
public class ViewFaculty extends javax.swing.JPanel {

    /**
     * Creates new form ViewFaculty
     */
    LibrarySystem ugat;
    DefaultTableModel mod;
    MySQLAPI api;
    public ViewFaculty(LibrarySystem root) {
        initComponents();
           this.ugat = root;
        this.setSize(540, 283);
       this.setLocation(230, 5);
       this.setBackground(new Color(0,0,0,0));
       
        mod = (DefaultTableModel)this.tblFaculty.getModel();
       
       tblFaculty.setSelectionBackground(new Color(51,153,255));
       tblFaculty.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     tblFaculty.getTableHeader().setReorderingAllowed(false);
       //code for diabling editing column
       for(int x=0;x<tblFaculty.getColumnCount();x++){
       Class<?> colClass = tblFaculty.getColumnClass(x);
       tblFaculty.setDefaultEditor(colClass, null);
       }
       
     api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");

       this.refreshFaculty("*", "*");
    }
    
    
    public void refreshFaculty(String cat,String field){
   ArrayList<Faculty> fac = api.getAllFaculty(cat, field);
   mod.setRowCount(0);
   
  for(int x=0;x<fac.size();x++){
  Faculty f = (Faculty)fac.get(x);
  Date d = new Date(Long.parseLong(f.getDateAdded()));
  mod.addRow(new Object[]{f.getId(),f.getFullName(),d.toLocaleString()});
  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFac = new javax.swing.JTextField();
        cboCat = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        txtFac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFacKeyReleased(evt);
            }
        });
        add(txtFac);
        txtFac.setBounds(110, 2, 290, 29);

        cboCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "First Name", "Middle Name", "Last Name" }));
        add(cboCat);
        cboCat.setBounds(396, 1, 110, 30);

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Faculty Added", "FullName", "Date Added"
            }
        ));
        jScrollPane1.setViewportView(tblFaculty);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 540, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewBook.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacKeyReleased
        // TODO add your handling code here:
        this.refreshFaculty(cboCat.getSelectedItem().toString(), txtFac.getText());
    }//GEN-LAST:event_txtFacKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFaculty;
    private javax.swing.JTextField txtFac;
    // End of variables declaration//GEN-END:variables
}
