/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Biben
 */
public class ViewLibrarian extends javax.swing.JPanel {

    /**
     * Creates new form ViewLibrarian
     */
    DialogLarge dlg;
    MySQLAPI api;
     DefaultTableModel mod=null;
     String que;
      SimpleDateFormat sdf;
    public ViewLibrarian(DialogLarge lrg) {
        initComponents();
        this.dlg = lrg;
        this.dlg.setSize(630, 335);
        this.dlg.setLocation(400, 300);
        this.dlg.setUndecorated(true);
       
        tblLibrarian.setSelectionBackground(new Color(51,153,255));
      
        api=new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");
        que = "SELECT librarian_id, f_name, m_name,l_name,  ";
        que += "username, password,address,birthdate,personal_question,personal_answer ";
        que += ",position_lib , date_hired FROM TblLibrarian ";
        
       ArrayList<Librarian> arr = api.getLibrarianFilter("*", "*");
    sdf =new SimpleDateFormat("MM/dd/YYYY");
        mod =(DefaultTableModel)tblLibrarian.getModel();
       tblLibrarian.setModel(mod);
        System.out.println(arr.size()+"laki");
        for(int x=0;x<arr.size();x++){
      // TableModel mod =tblLibrarian.getModel();
            Librarian indi = (Librarian)arr.get(x);
            String buo = indi.getFName()+" "+indi.getMName()+" "+indi.getLName();
         //   System.out.println("name "+buo);
           Date dHired = new Date(Long.parseLong(indi.getDateHired()));
       mod.addRow(new Object[]{indi.getId(),buo,indi.getPosition(),sdf.format(dHired)});
        //tblLibrarian.getModel().
        }
        
        
      
         
         for(int x=0;x<tblLibrarian.getColumnCount();x++){
         Class<?> colClass = tblLibrarian.getColumnClass(x);
         tblLibrarian.setDefaultEditor(colClass, null);
         }
         
        int bil=this.api.countTable("TblLibrarian");
      lblTotalLib.setText(lblTotalLib.getText()+" "+bil);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCloseViewAdmin = new javax.swing.JLabel();
        txtSearchLib = new javax.swing.JTextField();
        cboCategory = new javax.swing.JComboBox();
        sclRootTable = new javax.swing.JScrollPane();
        tblLibrarian = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotalLib = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblCloseViewAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialogClose.png"))); // NOI18N
        lblCloseViewAdmin.setText("jLabel2");
        lblCloseViewAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseViewAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseViewAdminMouseClicked(evt);
            }
        });
        add(lblCloseViewAdmin);
        lblCloseViewAdmin.setBounds(605, 5, 20, 15);

        txtSearchLib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchLibKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchLibKeyReleased(evt);
            }
        });
        add(txtSearchLib);
        txtSearchLib.setBounds(310, 32, 200, 27);

        cboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Firstname", "Middlename", "Lastname", "LibrarianID", "Position", "Date_hired" }));
        add(cboCategory);
        cboCategory.setBounds(505, 33, 100, 25);

        sclRootTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.darkGray));
        sclRootTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblLibrarian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        tblLibrarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Librarian ID", "Full Name", "Position", "Date Hired"
            }
        ));
        tblLibrarian.setGridColor(new java.awt.Color(255, 255, 255));
        tblLibrarian.setShowHorizontalLines(false);
        sclRootTable.setViewportView(tblLibrarian);

        add(sclRootTable);
        sclRootTable.setBounds(185, 58, 435, 230);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Search");
        add(jLabel3);
        jLabel3.setBounds(210, 38, 60, 15);

        lblTotalLib.setText("Total Librarian: ");
        add(lblTotalLib);
        lblTotalLib.setBounds(30, 270, 120, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewLibrarian.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setRequestFocusEnabled(false);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseViewAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseViewAdminMouseClicked
        // TODO add your handling code here:
        this.dlg.dispose();
    }//GEN-LAST:event_lblCloseViewAdminMouseClicked

    private void txtSearchLibKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchLibKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtSearchLibKeyPressed

    private void txtSearchLibKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchLibKeyReleased
        // TODO add your handling code here:
           mod.setRowCount(0);  
    ArrayList<Librarian> arr=api.getLibrarianFilter(cboCategory.getSelectedItem()+"", txtSearchLib.getText());
       // System.out.println(cboCategory.getSelectedItem()+"");
    for(int x=0;x<arr.size();x++){
    Librarian lib =(Librarian)arr.get(x);
    this.addRowToTable(lib);
    }
       
    }//GEN-LAST:event_txtSearchLibKeyReleased

    public void addRowToTable(Librarian indi){
      
        String buo = indi.getFName()+" "+indi.getMName()+" "+indi.getLName();
        Date dHired = new Date(Long.parseLong(indi.getDateHired()));
       mod.addRow(new Object[]{indi.getId(),buo,indi.getPosition(),sdf.format(dHired)});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCloseViewAdmin;
    private javax.swing.JLabel lblTotalLib;
    private javax.swing.JScrollPane sclRootTable;
    private javax.swing.JTable tblLibrarian;
    private javax.swing.JTextField txtSearchLib;
    // End of variables declaration//GEN-END:variables
}
