/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Biben
 */
public class ViewStudent extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudent
     */
    LibrarySystem ugat;
    DefaultTableModel mod;
    MySQLAPI api;
    public ViewStudent(LibrarySystem root) {
        initComponents();
        this.ugat = root;
        this.setSize(540, 283);
       this.setLocation(230, 5);
       this.setBackground(new Color(0,0,0,0));
       
       
        mod = (DefaultTableModel)this.tblStudent.getModel();
       
       tblStudent.setSelectionBackground(new Color(51,153,255));
       tblStudent.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     tblStudent.getTableHeader().setReorderingAllowed(false);
       //code for diabling editing column
       for(int x=0;x<tblStudent.getColumnCount();x++){
       Class<?> colClass = tblStudent.getColumnClass(x);
       tblStudent.setDefaultEditor(colClass, null);
       }
       
     api = new MySQLAPI("jdbc:mysql://localhost:3306/db_library","root","");

       this.refreshTable("*","*");
      
       
    }
    
    public void refreshTable(String field,String da){
        mod.setRowCount(0);
   ArrayList<Student> st =api.getStudentFilter(field, da);
   for(int x=0;x<st.size();x++){
   Student s = (Student)st.get(x);
   String sec = s.getGradeSection();
   if(s.getStatus().equals(Student.GRADUATED)){
   sec = Student.GRADUATED;
   }else if(s.getStatus().equals(Student.DROPPED)){
   sec = Student.DROPPED;
   }
   mod.addRow(new Object[]{s.getStudentNo(),s.getFullName(),sec,s.getBirthdate()});
   
   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        cboSearch = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnMove = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();

        setLayout(null);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch);
        txtSearch.setBounds(110, 2, 290, 29);

        cboSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "StudNo", "FirstName", "MiddleName", "LastName", "Grade-Section", "Birthdate" }));
        add(cboSearch);
        cboSearch.setBounds(396, 1, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/viewBook.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 30);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Number", "Full Name", "Year-Section", "Birthdate"
            }
        ));
        tblStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 28, 535, 200);

        btnMove.setText("Move Section");
        btnMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveActionPerformed(evt);
            }
        });
        add(btnMove);
        btnMove.setBounds(420, 230, 120, 25);

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });
        add(btnDrop);
        btnDrop.setBounds(319, 230, 90, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        
        this.refreshTable(cboSearch.getSelectedItem().toString(),txtSearch.getText());
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
        String studNo =mod.getValueAt(tblStudent.getSelectedRow(), 0).toString();
       DialogLarge dl= new DialogLarge(this.ugat,"as",true);
       dl.coverFrame(this.ugat.getCoverBlur());
       Student st=api.getSpecificStudent(Integer.parseInt(studNo));
       dl.addPanel(new StudentLogged(dl,st));
       dl.executeDialog();
        dl.hideCoverFrame(this.ugat.getCoverBlur());
        }else{
         String studNo =mod.getValueAt(tblStudent.getSelectedRow(), 0).toString();
            Student s = api.getSpecificStudent(Integer.parseInt(studNo));
            if(s.getStatus().equals(Student.DROPPED)){
            this.btnDrop.setText("Undrop");
            }else{
            btnDrop.setText("Drop");
            }
        }
    }//GEN-LAST:event_tblStudentMouseClicked

    private void btnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveActionPerformed
        // TODO add your handling code here:
        
       int pili = this.tblStudent.getSelectedRow();
       if(pili==-1){
       
       LibrarySystem.showError("Select specific student!", "Move student", this);
       }else{
           String studNo =this.mod.getValueAt(pili, 0).toString();
           Student s = api.getSpecificStudent(Integer.parseInt(studNo));
        DialogLarge dialog = new DialogLarge(ugat,"as",true);
        dialog.addPanel(new MoveStudent(dialog,s));
        dialog.coverFrame(ugat.getCoverBlur());
        dialog.executeDialog();
        dialog.hideCoverFrame(ugat.getCoverBlur());
       this.refreshTable("*", "*");
       }
       
    }//GEN-LAST:event_btnMoveActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        int choice = this.tblStudent.getSelectedRow();
        if(choice==-1){
        LibrarySystem.showError("Select specific student to drop!", "Failed to drop", this);
        }else{
       String studNo = mod.getValueAt(choice, 0).toString();
      Student s= api.getSpecificStudent(Integer.parseInt(studNo));
      if(s.getStatus().equals(Student.GRADUATED)){
      LibrarySystem.showError(s.getFullName()+" is already  graduated!","Failed to drop", this);
      }else if(s.getStatus().equals(Student.DROPPED)){
     int pili=  LibrarySystem.showConfirmation(s.getFullName()+" is already  dropped!\nDo you want to undrop this student?","Drop", this);
      if(pili==0){
      api.updateData("TblStudent", "status", Student.ON_SCHOOL, "stud_no",s.getStudentNo() );
      LibrarySystem.showMessage(s.getFullName()+" is successfully undropped.", "Undrop", this);
      }
      
      
      }else{
      int ch=LibrarySystem.showConfirmation("Are you sure to drop this student?\n"+s.getFullName(), "Drop student", this);
            if(ch==0){
            api.updateData("TblStudent", "status", Student.DROPPED, "stud_no", studNo);
            LibrarySystem.showMessage("Successfully dropped!", "Drop Student", this);
            }   
      }//end of lese
       this.refreshTable("*", "*");
        }//ne dof lese
    }//GEN-LAST:event_btnDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDrop;
    public javax.swing.JButton btnMove;
    private javax.swing.JComboBox cboSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
